name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_build_command: "cd AudioWorkstation/Guest && ./build.sh"
      linux_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "5.10"}]'
      enable_windows_checks: false
      
  wasm-sdk:
    name: WebAssembly Swift SDK
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_wasm_sdk_build: true
      enable_linux_checks: false
      enable_windows_checks: false
      swift_flags: --package-path AudioWorkstation/Guest --product Plotter
      swift_nightly_flags: --package-path AudioWorkstation/Guest --product Plotter

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift"
      api_breakage_check_enabled: false
      unacceptable_language_check_enabled: true
      license_header_check_enabled: false
      broken_symlink_check_enabled: true
      format_check_enabled: false
