name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  audio-workstation-guest:
    name: Build AudioWorkstation Plugins
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_embedded_wasm_sdk_build: true
      enable_linux_checks: false
      enable_macos_checks: false
      enable_windows_checks: false
      swift_flags: --package-path AudioWorkstation/Guest --product Plotter

  audio-workstation-host:
    name: Build AudioWorkstation Server
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_checks: true
      linux_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "6.0"}]'
      enable_windows_checks: false
      swift_flags: --package-path AudioWorkstation/ServerHost

  webgpu-demo:
    name: Build WebGPU Demo
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_embedded_wasm_sdk_build: true
      wasm_exclude_swift_versions: '[{"swift_version": "nightly-6.2"}]'
      enable_linux_checks: false
      enable_macos_checks: false
      enable_windows_checks: false
      swift_flags: --package-path WebGPUDemo

  dom-ref-types:
    name: Build DOMRefTypes Demo
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_embedded_wasm_sdk_build: true
      enable_linux_checks: false
      enable_macos_checks: false
      enable_windows_checks: false
      swift_flags: --package-path DOMRefTypes

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift"
      api_breakage_check_enabled: false
      unacceptable_language_check_enabled: true
      license_header_check_enabled: false
      broken_symlink_check_enabled: true
      format_check_enabled: true
