name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs: 
  audio-workstation:
    name: Build AudioWorkstation
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_wasm_sdk_build: true
      enable_linux_checks: false
      enable_windows_checks: false
      swift_flags: --package-path AudioWorkstation/Guest --product Plotter
      swift_nightly_flags: --package-path AudioWorkstation/Guest --product Plotter

  webgpu-demo:
    name: Build WebGPUDemo
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_wasm_sdk_build: true
      enable_linux_checks: false
      enable_windows_checks: false
      swift_flags: --package-path WebGPUDemo
      swift_nightly_flags: --package-path WebGPUDemo
      
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift"
      api_breakage_check_enabled: false
      unacceptable_language_check_enabled: true
      license_header_check_enabled: false
      broken_symlink_check_enabled: true
      format_check_enabled: false
